---
text:
  - talker: pnj$0
    file:
      fr: ../chunks/test.txt
      en: ../chunks/test.txt
characters:
  pnj$0:
    name: Bolloré
    rythm: 0.025
    font: patapa
    fontSize: 25
    bubble: BlueBubble
  pnj$1:
    name: Babtou
    rythm: 0.025
    font: patapa
    fontSize: 25
    bubble: PurpleBubble
triggers:
  - id: 1
    settings:
      rythm: 1
      font: patapa
settings:
  picture: PrinceOfTunis
  presentator: Moulard
