---
text:
  - talker: narrator
    file:
      fr: ../chunks/scene1.txt
      en: ../chunks/scene1.txt
choice:
  yes:
    - talker: narrator
      file:
        fr: ../chunks/scene1.txt
        en: ../chunks/scene1.txt
  no:
    - talker: narrator
      file:
        fr: ../chunks/scene1.txt
        en: ../chunks/scene1.txt
characters:
  narrator:
    name: Narrateur
    rythm: 0.05
    font: basic
    fontSize: 25
    bubble: bbrown
  guillemot:
    name: Guillemot
    rythm: 0.05
    font: basic
    fontSize: 25
    bubble: bpurple
  bollore:
    name: Bolloré
    rythm: 0.05
    font: basic
    fontSize: 25
    bubble: bblue
  moulard:
    name: Robert Moulard
    rythm: 0.05
    font: basic
    fontSize: 25
    bubble: bgreen
triggers:
  - id: 1
    settings:
      rythm: 1
      fontSize: 100
  - id: 2
    settings:
      rythm: 0
      fontSize: 60
  - id: 3
    settings:
      rythm: 0.025
      fontSize: 30
  - id: 4
    settings:
      rythm: 0.01
      fontSize: 40
  - id: 5
    settings:
      rythm: 0.045
      fontSize: 18
settings:
  picture: PrinceOfTunis
  presentator: Moulard

days:
  - One:
    - PrinceOfTunis
    - Bails
    - Bouille
