---
text:
  - talker: narrator
    file:
      fr: ../chunks/scene1.txt
      en: ../chunks/scene1.txt
characters:
  narrator:
    name: Narrateur
    rythm: 0.05
    font: basic
    fontSize: 25
    bubble: bbrown
  guillemot:
    name: Guillemot
    rythm: 0.05
    font: basic
    fontSize: 25
    bubble: bpurple
  bollore:
    name: Bolloré
    rythm: 0.05
    font: basic
    fontSize: 25
    bubble: bblue
  moulard:
    name: Robert Moulard
    rythm: 0.05
    font: basic
    fontSize: 25
    bubble: bgreen
triggers:
  - id: 1
    settings:
      rythm: 1
  - id: 2
    settings:
      rythm: 0
      fontSize: 60
  - id: 3
    settings:
      rythm: 0.01
      fontSize: 30
settings:
  picture: PrinceOfTunis
  presentator: Moulard

days:
  - One:
    - PrinceOfTunis
    - Bails
    - Bouille
