---
text:
  - talker: pnj$0
    file:
      fr: ../chunks/test.txt
      en: ../chunks/test.txt
characters:
  pnj$0:
    name: Bolloré
    rythm: 0.025
    font: patapa
    fontSize: 25
    bubble: testFace
  pnj$1:
    name: Guillemot
    rythm: 0.025
    font: patapa
    fontSize: 25
    bubble: testFace
triggers:
  - id: 1
    settings:
      rythm: 1
      font: patapa
detail:
  picture: PrinceOfTunis

days:
  - One:
    - PrinceOfTunis
    - Bails
    - Bouille
